### ISSUE TITLE
Unable to run JAR file from command line

### ISSUE THREAD

**Issue by eerodrigues** [Papr3ka/RoboChess#1]
When I downloaded the release and tried to run `java -jar becker.jar` from the command line, I received the error `no main manifest attribute, in becker.jar`. I believe some extra steps during packaging are needed to make this JAR an executable. Although I'm not too familiar with Java, I think this is the standard way to run packages (please correct me if I am wrong).

Otherwise, if there is another way to run your program, perhaps the steps could be documented in the README.

Thanks in advance! I'm really interested in checking out your program :)

**Comment by Papr3ka** [comment]
`becker.jar` is not supposed to be executable. It is a library used for the program. I assume you are trying to run the RoboChess program. Just download the `RoboChess.jar` file from releases and run it.

**Comment by eerodrigues** [comment]
Ahh, my mistake then, I missed `RoboChess.jar` the first time and that executes as expected for me. Nice work on the program! Thanks for updating the README too :)
